[package]
name = "moolooite"
version = "0.1.0"
edition = "2021"

[dependencies]
serenity = { version = "0.11.5", default-features = false, features = ["model"] }
tokio = { version = "1.23.0", features = ["rt-multi-thread"] }
